### ISSUE TITLE
[Feature] Support for object-level field permissions

### ISSUE THREAD

**Issue by ajhodges** [InterSIS/django-rest-serializer-field-permissions#22]
For more complex object-level field permissions, I think it could be beneficial to pass the instance that is currently being checked to the FieldPermission. This is pretty simply achieved by wrapping Serializer.to_representation(instance) and keeping track of this instance in a Serializer.current_instance variable. (This is necessary for ListSerializers, as the Serializer.instance field contains the entire list in that case).

I have tested/implemented this in a branch on my fork, and will be opening a PR for review.

**Comment by JASchilz** [comment]
Hi @ajhodges  . I think that this is probably an awesome suggestion, and worthwhile to implement.

I've recently updated my README regarding new features. The short of it is that I've found that:
  * I haven't used this library myself in a few years.
  * It takes me a day or two to spin myself up on the library to where I can responsibly and safely consider the impacts of any given change to the user base. I can't currently prioritize that spin-up time every few months as people bring up really good ideas like this.
  * So, I'm advertising this library as under _maintenance mode_: I'll add new drop-in fields as Django/DRF create them, but otherwise I'll just maintain support for the current major versions of Django and DRF.

Thank you for engaging with this library, and I'm sorry that I won't be able to implement this good idea.
