### ISSUE TITLE
[Feature] Support for converting the existed fields

### ISSUE THREAD

**Issue by Char2sGu** [InterSIS/django-rest-serializer-field-permissions#28]
How about adding permissions to automatically generated fields by specifying the permissions in Meta?

```Python
    class Meta:
        model = ...
        fields = [..., 'state']
        permissions = {
            'state': [...],
        }
```

**Comment by JASchilz** [comment]
Hi @TheNightmareX . I think that this is probably an awesome suggestion, and worthwhile to implement.

I've recently updated my README regarding new features. The short of it is that I've found that:
  * I haven't used this library myself in a few years.
  * It takes me a day or two to spin myself up on the library to where I can responsibly and safely consider the impacts of any given change to the user base. I can't currently prioritize that spin-up time every few months as people bring up really good ideas like this.
  * So, I'm advertising this library as under _maintenance mode_: I'll add new drop-in fields as Django/DRF create them, but otherwise I'll just maintain support for the current major versions of Django and DRF.

Thank you for engaging with this library, and I'm sorry that I won't be able to implement this good idea.
